# Generated by Django 4.2.20 on 2025-05-20 22:11

import apps.auth_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.auth_user.models.user_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
