# Generated by Django 5.2 on 2025-05-03 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('Comming soon', 'COMMING SOON'), ('Registration', 'REGISTRATION'), ('Ongoing', 'ONGOING'), ('Closed', 'CLOSED')], max_length=15, null=True)),
                ('inscription_start', models.DateTimeField()),
                ('inscription_end', models.DateTimeField()),
                ('partners', models.ManyToManyField(related_name='partner', to='partner.partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionPhase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.JSONField(default=dict)),
                ('dataset_urls', models.ManyToManyField(related_name='dataset', to='dataset.dataset')),
                ('competition_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitionphase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
