# Generated by Django 4.2.20 on 2025-05-20 22:11

import apps.competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataset", "0001_initial"),
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="metric",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="competition_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.competition.models.competition_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="dataset_urls",
            field=models.ManyToManyField(
                related_name="datasetfile", to="dataset.datasetfile"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="competitionphase",
            name="name",
            field=models.CharField(
                choices=[("national", "National"), ("international", "International")],
                max_length=20,
            ),
        ),
    ]
