# Generated by Django 4.2.20 on 2025-05-20 22:11

import apps.partner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.partner.models.partner_logo_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
