# Generated by Django 4.2.20 on 2025-04-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submission", "0001_initial"),
        ("competition", "0001_initial"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="team.team",
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="competition_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competition.competitionphase",
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="team.team"
            ),
        ),
    ]
