# Generated by Django 4.2.20 on 2025-05-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="limit",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="Leaderboard",
        ),
    ]
