# Generated by Django 4.2.20 on 2025-05-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamjoinrequest",
            name="team_join_request_status",
            field=models.CharField(
                choices=[("invitation", "Invitation"), ("demande", "Demande")],
                default="invitation",
                max_length=20,
            ),
        ),
    ]
