# Generated by Django 5.1.7 on 2025-03-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_datatour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='compétition_phase',
            new_name='competition_phase',
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/partners/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
