# Generated by Django 5.1.7 on 2025-03-09 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_datatour", "0002_partner_created_at_partner_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="compétition_phase",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competition_phase",
                to="back_datatour.competitionphase",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="users",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
