# Generated by Django 5.1.7 on 2025-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_datatour", "0002_users_is_verified_users_verification_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="compétition_phase",
            new_name="competition_phase",
        ),
        migrations.AddField(
            model_name="users",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
