# Generated by Django 5.1.7 on 2025-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_datatour", "0003_alter_announcement_id_alter_challenge_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
