# Generated by Django 5.1.7 on 2025-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_datatour", "0003_alter_comment_compétition_phase_alter_comment_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="description",
        ),
        migrations.AddField(
            model_name="partner",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/partners/"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
