# Generated by Django 5.1.7 on 2025-03-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_datatour", "0004_remove_partner_description_partner_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="description",
        ),
        migrations.AddField(
            model_name="challenge",
            name="additionals_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="data_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="evaluate_criteria",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="objective",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="submission_format",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="task_participants",
            field=models.TextField(blank=True, null=True),
        ),
    ]
