# Generated by Django 5.1.7 on 2025-03-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "back_datatour",
            "0005_alter_competition_id_alter_competitionphase_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="profession",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
